name: notify-common-expense / test

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/notify-common-expense--test.yaml
      - notify-common-expense/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/notify-common-expense--test.yaml
      - notify-common-expense/**

defaults:
  run:
    working-directory: notify-common-expense

jobs:
  lint:
    needs: format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: aquaproj/aqua-installer@v4.0.4
        with:
          aqua_version: v2.56.6
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - run: github-comment exec --token ${{ secrets.GITHUB_TOKEN }} -- npm ci
      - run: github-comment exec --token ${{ secrets.GITHUB_TOKEN }} -- npm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: aquaproj/aqua-installer@v4.0.4
        with:
          aqua_version: v2.56.6
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - run: github-comment exec --token ${{ secrets.GITHUB_TOKEN }} -- npm ci
      - run: github-comment exec --token ${{ secrets.GITHUB_TOKEN }} -- npm run format
      - uses: int128/update-generated-files-action@v2

  test:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: aquaproj/aqua-installer@v4.0.4
        with:
          aqua_version: v2.56.6
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - run: github-comment exec --token ${{ secrets.GITHUB_TOKEN }} -- npm ci
      - run: github-comment exec --token ${{ secrets.GITHUB_TOKEN }} -- npm test